### ISSUE TITLE
unloading sd module

### ISSUE THREAD

**Issue by farfromrefug** [andy-shev/u-boot#11]
Recently i stumble upon the issue where some EDison GPIOs where could not write on them because they were reserved for the SD:
https://communities.intel.com/thread/77677

I know i can compile a kernel without that module. But i would prefer to be able to unload /load it at runtime.
I don't enought about kernels to actually know where to look to see if this kernel allows this.
Can you guide me?

Thanks

**Comment by andy-shev** [comment]
I'm not sure I understand why this issue is created against U-Boot. U-boot has no GPIO support for Intel Tangier, so, it doesn't affect it.

Feel free to file one in my linux repository.

**Comment by farfromrefug** [comment]
@andy-shev i was affraid i was postiing this in the wrong repo :s Will create an issue on your linux repo

Thanks
