### ISSUE TITLE
Build edison-v2017.01 fails

### ISSUE THREAD

**Issue by htot** [andy-shev/u-boot#5]
I checkout edison-v2017.01 then
- make edison_defconfig
- make -j4
(after finding I am missing the dtc, and installing that, run make -j4 again)
...
  CC      examples/standalone/hello_world.o
  LD      examples/standalone/libstubs.o
  LD      examples/standalone/hello_world
  OBJCOPY examples/standalone/hello_world.srec
  OBJCOPY examples/standalone/hello_world.bin
  LD      u-boot
  OBJCOPY u-boot.srec
  OBJCOPY u-boot-nodtb.bin
  SYM     u-boot.sym
  COPY    u-boot.bin
./scripts/check-config.sh u-boot.cfg ./scripts/config_whitelist.txt . 1>&2
Error: You must add new CONFIG options using Kconfig
The following new ad-hoc CONFIG options were detected:
CONFIG_INHERIT_GDT
CONFIG_SFI

Please add these via Kconfig instead. Find a suitable Kconfig
file and add a 'config' or 'menuconfig' option.

Is that normal or harmless? Did I need to clean before running make?

**Comment by andy-shev** [comment]
https://github.com/andy-shev/u-boot/issues/2

**Comment by htot** [comment]
Ok sorry, thought #2 was related to Yocto only.

**Comment by andy-shev** [comment]
No problem, development version is fixed and one has no such errors anymore.
