### ISSUE TITLE
[Feature Request] No DFU Timeout Patch?

### ISSUE THREAD

**Issue by bradjc** [andy-shev/u-boot#6]
Just wondering why the DFU timeout patch (https://github.com/01org/edison-u-boot/commit/5e966ccc3c65c18c9783741fa04e0c45e021780c) isn't included. It certainly makes flashing new images on Edisons easier.

Also, would you be willing to accept a PR if it was updated for the new version of u-boot?

**Comment by andy-shev** [comment]
Unfortunately I have no time for that. I have got one version (ported to new U-Boot) done by my colleague, but it's not ready for inclusion. If someone makes it upstream ready I will include into my branch.
