### ISSUE TITLE
Kernel doesn't boot with acpi branch u-boot

### ISSUE THREAD

**Issue by svenschwermer** [andy-shev/u-boot#9]
Hi! I compiled the acpi branch with edison_defconfig. And flashed it to my Edison. I'm using the andy-shev/linux kernel from the eds branch with the 4 extra patches applied as noted [here](https://edison.internet-share.com/wiki/ACPI#Prerequisites). When u-boot hands over to the kernel, nothing happens:
```
U-Boot 2017.11-rc1-00115-gd2ceea7 (Oct 15 2017 - 14:23:16 +0200)

CPU: x86_64, vendor Intel, device 406a8h
DRAM:  980.6 MiB
MMC:   mmc@ff3fc000: 0, mmc@ff3fa000: 1
In:    serial
Out:   serial
Err:   serial
Net:   No ethernet found.
ACPI: Writing ACPI tables at e4500
ACPI:    * FACS
ACPI:    * DSDT
Fix up global NVS in DSDT to 0x000e4d80
ACPI:    * FADT
ACPI:    * MADT
ACPI:    * MCFG
current = e5010
ACPI: done

=> run bootcmd_edsboot
reading vmlinuz.efi
7811344 bytes read in 346 ms (21.5 MiB/s)
reading initrd
1770856 bytes read in 93 ms (18.2 MiB/s)
Valid Boot Flag
Setup Size = 0x00003e00
Magic signature found
Using boot protocol version 2.0d
Linux kernel version 4.13.0+ (sven@arch-pc) #31 SMP Sun Oct 15 15:31:43 CEST 2017
Building boot_params at 0x00090000
Loading bzImage at address 100000 (7795472 bytes)
Magic signature found
Initial RAM disk at linear address 0x03000000, size 16777216 bytes
Kernel command line: "console=tty1 console=ttyS2,115200n8 rootfstype=ramfs rw ignore_loglevel apic=debug acpi.debug_layer=0xffff056d acpi.debug_level=0x0000200f"

Starting kernel ...
```
Did I miss anything or should this work?

**Comment by andy-shev** [comment]
Yeah, sorry for that, you need to apply few more patches to the kernel. They are published on my Bitbucket page (not here, since it's WIP): https://bitbucket.org/andy-shev/linux/branch/topic/eds-acpi

**Comment by htot** [comment]
And here: https://github.com/htot/linux/tree/eds-4.14-acpi

**Comment by htot** [comment]
The kernel without the patches mentioned above will boot with acpi=off on the command line.

**Comment by andy-shev** [comment]
I guess this issue had been fixed for a while.
I'm closing this, though ACPI related work is still in progress.
